// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-Unity",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-Unity", targets: ["AATKit-Unity"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-Unity",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATUnityAdapter",
                    "AATUnityAds",
                    "AATUnityCoherenceLib",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-Unity"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATUnityAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/AATUnityAdapter.zip",
            checksum: "9a33e1a41fd29424fb2b7a71727009346a6e536abf74becdd90eb144fa0c90c3"
        ),
        .binaryTarget(
            name: "AATUnityAds",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/UnityAds.zip",
            checksum: "b2b11cda258512e18d207fd736328f1b20fbdef265003ce0b2f161cc89020f66"
        ),
        .binaryTarget(
            name: "AATUnityCoherenceLib",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/UnityCoherenceLib.zip",
            checksum: "ad69f9bf2eee3ed8ade8610af2d4959b7160b2f692730183f4b35b6efb5b1ed4"
        ),
    ]
)
